apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
  {{- range .Values.bootstrapRoleARNs }}
  - rolearn: {{ . | quote }}
    username: system:node:{{ "{{" }}EC2PrivateDNSName{{ "}}" }}
    groups:
      - system:bootstrappers
      - system:nodes
  {{- end }}
  {{- range .Values.adminRoleARNs }}
  - rolearn: {{ . | quote }}
    username: admin
    groups:
    - system:masters
  {{- end }}
  {{- range .Values.sreRoleARNs }}
  - rolearn: {{ . | quote }}
    username: sre
    groups:
    - sre
  {{- end }}
  {{- range .Values.devRoleARNs }}
  - rolearn: {{ . | quote }}
    username: dev
    groups:
    - dev
  {{- end }}
