---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.fluxNamespace }}
  annotations:
    iam.amazonaws.com/permitted: {{ .Values.fluxPermittedRolesRegex | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: flux
  name: flux
  namespace: {{ .Values.fluxNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: flux
  name: flux
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: flux
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: {{ .Values.fluxNamespace }}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.flux.weave.works
spec:
  group: flux.weave.works
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    shortNames:
    - hr
  scope: Namespaced
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ['values', 'chart']
          properties:
            releaseName:
              type: string
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            valueFileSecrets:
              type: array
              items:
                type: object
                required: ['name']
                properties:
                  name:
                    type: string
            values:
              type: object
            chart:
              oneOf:
              - required: ['git', 'path']
                properties:
                  git:
                    type: string
                    format: git # not defined by OAS
                  path:
                    type: string
                  ref:
                    type: string
              - required: ['repository', 'name', 'version']
                properties:
                  repository:
                    type: string
                    format: url # not defined by OAS
                  name:
                    type: string
                  version:
                    type: string
                    format: semver # not defined by OAS
                  chartPullSecret:
                    properties:
                      name:
                        type: string
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
  namespace: {{ .Values.fluxNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux-helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux-helm-operator
      annotations:
        iam.amazonaws.com/role: {{ .Values.fluxHelmOperatorRole | quote }}
    spec:
      serviceAccount: flux
      volumes:
      # The following volume is for using a customised known_hosts file,
      # which you will need to do if you host your own git repo rather
      # than using github or the like. You'll also need to mount it
      # into the container, below.
      #
      # You may also wish to provide an ssh_config file,
      # mentioning more than one `IdentityFile`; for instance, if you're
      # using more than one GitHub repo. NB the entry key should be
      # "config" rather than "ssh_config" if mounted in ~/.ssh/.
      #
      # - name: sshdir
      #   configMap:
      #     name: flux-ssh-config
      #     defaultMode: 0400
      #
      # You will need this volume if you're using a git repo that
      # needs an SSH key for access; e.g., a GitHub deploy key. If
      # you're using just one such repo, the default ssh_config
      # already points at /etc/fluxd/ssh/identity as a key. If you
      # want to use more than one key, you'll need to provide your own
      # ssh_config above, with an `IdentityFile` entry matching each
      # key in the secret mentioned here.
      #
      # - name: git-key
      #   secret:
      #     secretName: flux-git-deploy
      #     defaultMode: 0400 # when mounted read-only, we won't be able to chmod
      #
      # These two volumes are for mounting a repositories.yaml file,
      # and providing a cache directory. The latter is needed because
      # mounting the former will make the cache/ directory read-only.
      #
      # - name: repositories-yaml
      #   secret:
      #     secretName: flux-helm-repositories
      # - name: repositories-cache
      #   emptyDir: {}

      containers:
      - name: flux-helm-operator
        # There are no ":latest" images for helm-operator. Find the most recent
        # release or image version at https://quay.io/weaveworks/helm-operator
        # and replace the tag here.
        image: govsvc/helm-operator:gds-master-b7e03cb3
        imagePullPolicy: IfNotPresent
        args:
        - --charts-sync-interval=1m
        - --update-chart-deps=false
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        # Include this if you need to mount a customised known_hosts or ssh_config
        # file; you'll also need the volume declared above.
        # - name: sshdir
        #   mountPath: /root/.ssh
        #   readOnly: true
        # - name: git-key
        #   mountPath: /etc/fluxd/ssh
        # - name: repositories-yaml
        #   mountPath: /var/fluxd/helm/repository
        # - name: repositories-cache
        #   mountPath: /var/fluxd/helm/repository/cache
...
